"""Shared-State Architecture v3: Unrolled encoder/decoder with separate weights.

Encoder and decoder act on different data (input bytes vs generated bytes),
so they have separate weights. This is like unrolling an RNN but with
specialized instances.

Architecture (N=2, M=2):
  encoder_1(byte_1, init_state) → state_1
  encoder_2(byte_2, state_1) → state_2
  patch_model(state_2) → transformed_state
  decoder_1(transformed_state, init_state) → byte_3, decoder_state_1
  decoder_2(byte_3, decoder_state_1) → byte_4, decoder_state_2

Loss:
  encoder_loss: predict byte_2 from state_1, byte_3 from state_2
  decoder_loss: predict byte_4 from decoder_state_1, byte_5 from decoder_state_2
"""

from __future__ import annotations

import torch
import torch.nn as nn
import torch.nn.functional as F

from domains.rwkv.rwkv_nano import RWKVBlock, count_params


class EncoderInstance(nn.Module):
    """Single encoder instance: processes one byte, updates state."""
    
    def __init__(self, vocab_size: int, dim: int, n_layers: int):
        super().__init__()
        self.dim = dim
        self.embed = nn.Embedding(vocab_size, dim)
        self.blocks = nn.ModuleList([RWKVBlock(dim) for _ in range(n_layers)])
        self.ln = nn.LayerNorm(dim)
        # Prediction head: predict next byte from state
        self.head = nn.Linear(dim, vocab_size)
        
    def forward(self, token: torch.Tensor, rwkv_state: dict | None = None):
        """
        Args:
            token: [B] byte token (single byte per batch)
            rwkv_state: previous RWKV state
        Returns:
            hidden_state: [B, dim] hidden state tensor (for patch model)
            rwkv_state: updated RWKV state (for next encoder instance)
            logits: [B, vocab_size] prediction of next byte
        """
        h = self.embed(token)  # [B, dim]
        h = h.unsqueeze(1)  # [B, 1, dim]
        
        for block in self.blocks:
            h, rwkv_state = block(h, rwkv_state)
        
        h = self.ln(h)
        h = h.squeeze(1)  # [B, dim]
        hidden_state = h  # Save for patch model
        logits = self.head(h)  # [B, vocab_size]
        
        return hidden_state, rwkv_state, logits


class DecoderInstance(nn.Module):
    """Single decoder instance: generates one byte from state."""
    
    def __init__(self, vocab_size: int, dim: int, n_layers: int):
        super().__init__()
        self.dim = dim
        self.blocks = nn.ModuleList([RWKVBlock(dim) for _ in range(n_layers)])
        self.ln = nn.LayerNorm(dim)
        self.head = nn.Linear(dim, vocab_size)
        
    def forward(self, input_state: torch.Tensor, state: dict | None = None):
        """
        Args:
            input_state: [B, dim] state to generate from (transformed or previous decoder state)
            state: previous decoder RWKV state
        Returns:
            logits: [B, vocab_size] generated byte prediction
            decoder_state: updated decoder RWKV state
        """
        h = input_state.unsqueeze(1)  # [B, 1, dim]
        
        for block in self.blocks:
            h, state = block(h, state)
        
        h = self.ln(h)
        h = h.squeeze(1)  # [B, dim]
        logits = self.head(h)  # [B, vocab_size]
        
        return logits, state


class PatchModel(nn.Module):
    """Transforms encoder state into decoder input."""
    
    def __init__(self, dim: int, n_layers: int):
        super().__init__()
        self.dim = dim
        self.blocks = nn.ModuleList([RWKVBlock(dim) for _ in range(n_layers)])
        self.ln = nn.LayerNorm(dim)
        self.proj = nn.Linear(dim, dim)
        
    def forward(self, encoder_state: torch.Tensor):
        """
        Args:
            encoder_state: [B, dim] final encoder state
        Returns:
            transformed_state: [B, dim] state for decoder
        """
        h = encoder_state.unsqueeze(1)  # [B, 1, dim]
        
        for block in self.blocks:
            h, _ = block(h)
        
        h = self.ln(h)
        h = h.squeeze(1)  # [B, dim]
        transformed_state = self.proj(h)
        
        return transformed_state


class SharedStateUnrolled(nn.Module):
    """Unrolled shared-state architecture with shared weights (true RNN-style).
    
    Uses a single encoder and decoder, applied N times each.
    This is true RNN unrolling: same weights at each time step.
    """
    
    def __init__(
        self,
        vocab_size: int = 258,
        dim: int = 64,
        n_encoder_layers: int = 1,
        n_decoder_layers: int = 1,
        n_patch_layers: int = 1,
        n_encoder_steps: int = 2,  # N: number of encoder applications
        n_decoder_steps: int = 2,  # M: number of decoder applications
    ):
        super().__init__()
        self.dim = dim
        self.n_encoder_steps = n_encoder_steps
        self.n_decoder_steps = n_decoder_steps
        
        # Single encoder (applied N times)
        self.encoder = EncoderInstance(vocab_size, dim, n_encoder_layers)
        
        # Single decoder (applied M times)
        self.decoder = DecoderInstance(vocab_size, dim, n_decoder_layers)
        
        # Patch model
        self.patch_model = PatchModel(dim, n_patch_layers)
        
    def forward(self, tokens: torch.Tensor, targets: torch.Tensor):
        """
        Training forward pass.
        
        Args:
            tokens: [B, T] input byte tokens (need at least N+M bytes)
            targets: [B, T] target byte tokens
        Returns:
            loss: combined loss
            metrics: dict with individual losses
        """
        B, T = tokens.shape
        required_len = self.n_encoder_steps + self.n_decoder_steps
        
        if T < required_len:
            raise ValueError(f"Need at least {required_len} tokens, got {T}")
        
        # Encoder phase: process N bytes
        rwkv_state = None
        encoder_state = None  # Will hold the last hidden state
        encoder_losses = []
        
        for i in range(self.n_encoder_steps):
            byte = tokens[:, i]  # [B]
            target = targets[:, i + 1]  # [B] predict next byte
            
            encoder_state, rwkv_state, logits = self.encoder(byte, rwkv_state)
            
            # Loss: predict next byte
            loss = F.cross_entropy(logits, target)
            encoder_losses.append(loss)
        
        # Patch phase: transform encoder state
        transformed_state = self.patch_model(encoder_state)  # [B, dim]
        
        # Decoder phase: generate M bytes
        decoder_state = None
        decoder_losses = []
        
        for i in range(self.n_decoder_steps):
            # Input is transformed_state for first step, then embedding of the previous target token (teacher forcing)
            if i == 0:
                input_state = transformed_state
            else:
                prev_target_idx = self.n_encoder_steps + i - 1
                if prev_target_idx < T:
                    prev_target = targets[:, prev_target_idx]
                    input_state = self.encoder.embed(prev_target)
                else:
                    input_state = transformed_state
            
            logits, decoder_state = self.decoder(input_state, decoder_state)
            
            # Target: the actual next byte (prevents target leakage)
            target_idx = self.n_encoder_steps + i
            if target_idx < T:
                target = targets[:, target_idx]
                loss = F.cross_entropy(logits, target)
                decoder_losses.append(loss)
        
        # Total loss
        encoder_loss = sum(encoder_losses) / len(encoder_losses)
        decoder_loss = sum(decoder_losses) / len(decoder_losses) if decoder_losses else torch.tensor(0.0)
        total_loss = encoder_loss + decoder_loss
        
        metrics = {
            'encoder_loss': encoder_loss.item(),
            'decoder_loss': decoder_loss.item() if isinstance(decoder_loss, torch.Tensor) else decoder_loss,
        }
        
        return total_loss, metrics


if __name__ == "__main__":
    # Smoke test
    model = SharedStateUnrolled(
        vocab_size=258,
        dim=64,
        n_encoder_layers=1,
        n_decoder_layers=1,
        n_patch_layers=1,
        n_encoder_steps=2,
        n_decoder_steps=2,
    )
    
    print(f"Total params: {count_params(model):,}")
    print(f"  encoder: {count_params(model.encoder):,}")
    print(f"  decoder: {count_params(model.decoder):,}")
    print(f"  patch_model: {count_params(model.patch_model):,}")
    
    B, T = 2, 10
    tokens = torch.randint(2, 258, (B, T))
    targets = torch.randint(2, 258, (B, T))
    
    loss, metrics = model(tokens, targets)
    print(f"\nForward pass:")
    print(f"  loss: {loss.item():.4f}")
    print(f"  metrics: {metrics}")
    
    # Gradient sanity
    loss.backward()
    n_zero_grad = sum(
        1 for p in model.parameters() if p.grad is not None and p.grad.abs().sum() == 0
    )
    n_total = sum(1 for _ in model.parameters())
    print(f"\nGradient sanity:")
    print(f"  {n_zero_grad}/{n_total} params have zero gradient")
    print("Done.")
